version: '3.8'

services:
  mvc-app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_LOGGING__LOGLEVEL__DEFAULT=Debug
    ports:
      - "5000:8080"
      - "5001:8081"
    volumes:
      - ./src:/app/src:ro
      - ./logs:/app/logs
    restart: unless-stopped